### ISSUE TITLE
InvalidTagKey.Malformed: Tag specification must have at least one tag (error building packer image)

### ISSUE THREAD

**Issue by brannondorsey** [aws-samples/aws-efa-nccl-baseami-pipeline#3]
Building `nvidia-efa-ml-al2-eks.yml` (and perhaps other images) with Packer using the default spot instance type of `g4dn.8xlarge` fails. This appears to be related to https://github.com/hashicorp/packer-plugin-amazon/issues/92.

<img width="1056" alt="Screen Shot 2021-08-30 at 2 16 55 PM" src="https://user-images.githubusercontent.com/3193533/131385612-94fed8e7-8013-4e44-b602-70a7db5ef0d7.png">

## Steps to reproduce

* Clone this repo
* `cd nvidia-efa-ami_base`
* Update variables in `nvidia-efa-ml-al2-eks.yml` per README instructions
* `packer build nvidia-efa-ml-al2-eks.yml`

```
packer --version
1.7.4
```

**Comment by brannondorsey** [comment]
This issue appears to only occur when using spot instance builders. By building using On-Demand instances instead the issue is resolved:

<img width="477" alt="Screen Shot 2021-08-30 at 2 23 42 PM" src="https://user-images.githubusercontent.com/3193533/131386396-aaca6746-d307-4f46-b6a3-0fe4ff046468.png">

**Comment by amrragab8080** [comment]
This was introduced in the Packer 1.7.x branch the build pipeline uses 1.6.x and doesnt have this issue.
